Applied dmenu-alpha patch
So, this patch is somewhat cryptic.
First, there's this 'mysterious' variable called `border_width`
that's not defined anywhere. I added the variable myself.
The name `border_width` suggests type `unsigned int` because
widths can't be negative.
Then, when I tried to compile after manually patching the diff
file, a linker error occured, which said "undefined reference to `XRenderFindVisualFormat`".
The moment I saw that, I immediately thought that the config.mk
file must've not included a library object.
So, without much ambiguity, I added `-lXrender` to config.mk's
LIBS variable, and walla! it compiled successfully.